name: caltest

channels:
    - astropy
    - http://ssb.stsci.edu/astroconda
    - http://ssb.stsci.edu/conda-dev

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - stsci_sphinx_theme
    - jwst=0.7.8rc2
#   - pip:
#       - stsci
