name: calibration_pipeline_testing_tool

channels:
    - astropy
    - http://ssb.stsci.edu/astroconda

dependencies:
    - astropy
    - Cython
    - matplotlib
    - numpy
    - stsci_sphinx_theme
#   - pip:
#       - stsci
